// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSPWebApi.Models;

namespace PSPWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180818180614_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("PSPWebApi.Models.PspDbMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Label")
                        .IsRequired();

                    b.Property<string>("PspTable")
                        .IsRequired();

                    b.Property<string>("PspTimeCol");

                    b.Property<string>("PspValCol")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("PspDbMeasurements");

                    b.HasData(
                        new { Id = 1, Label = "Gujarat Demand MU", PspTable = "STATE_LOAD_DETAILS", PspTimeCol = "Date", PspValCol = "GujaratDemMu" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
